dist: bionic
language: cpp
compiler: gcc
sudo: required

script:
 - python -m pip install --upgrade pip
 - pip install --upgrade pygount
 - pygount libs -f summary -s c
 - source ./build.sh
 - source ./runtests.sh
