dist: bionic
language: cpp
compiler: gcc
sudo: required

addons:
  apt:
    packages:
       - valgrind

script:
 - source ./build.sh
 - valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no artifacts/offline
